// AUTO-GENERATED by better-intl. Do not edit by hand.
// Regenerated automatically by the Next.js plugin on dev/build.

/* eslint-disable */
import { createI18n } from "better-intl/runtime";

export const translations = {
	en: {
		components: {
			modules: {
				github: {
					contributions: {
						title: (v: { total: string }) => `${v.total} contributions in the last year to`,
						tooltip: (v: { count: string; date: string }) => `${v.count} contributions on ${v.date}`,
						less: "Less",
						more: "More",
					},
				},
				projects: {
					title: "Projects that i've worked on",
				},
			},
		},
	},
	pt: {
		components: {
			modules: {
				github: {
					contributions: {
						title: (v: { total: string }) => `${v.total} contribuições no último ano para`,
						tooltip: (v: { count: string; date: string }) => `${v.count} contribuições em ${v.date}`,
						less: "Menos",
						more: "Mais",
					},
				},
				projects: {
					title: "Projetos que eu trabalhei",
				},
			},
		},
	},
	es: {
		components: {
			modules: {
				github: {
					contributions: {
						title: (v: { total: string }) => `${v.total} contribuciones en el último año para`,
						tooltip: (v: { count: string; date: string }) => `${v.count} contribuciones en ${v.date}`,
						less: "Menos",
						more: "Más",
					},
				},
				projects: {
					title: "Proyectos en los que he trabajado",
				},
			},
		},
	},
} as const;

export type Locale = keyof typeof translations;

/** Runtime config for `better-intl/runtime`, baked into the helpers below. */
export const intlConfig = {
	"defaultLocale": "en",
	"locales": [
		"en",
		"pt",
		"es"
	],
	"storage": {
		"type": "cookie",
		"key": "locale"
	}
} as const;

// Helpers bound to `translations` + `intlConfig` once. Import `t` anywhere
// (sync on both client and server); call `setLocale()` once per request in the
// root layout; call `updateLocale(locale)` to persist a new preference.
const i18n = createI18n(translations, intlConfig);
export const { t, setLocale, updateLocale } = i18n;
