import { GeistSans as Geist } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body
        className={`${Geist.className} antialiased flex items-center justify-center w-screen h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
